version: "3.9"
services:
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "4000:4000"
    networks:
      - node_app_network
    depends_on:
      - db

  db:
    image: mysql:8.4.6
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - node_app_network
    volumes:
      - mysql_data_interview:/var/lib/mysql

volumes:
  mysql_data_interview:

networks:
  node_app_network:
    driver: bridge
