version: "3.9"
services:
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: mysql:8.0.43-bookworm
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
